FROM ubuntu:16.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git-all
RUN apt-get install -y iputils-ping
RUN apt-get install -y wget
RUN apt-get install -y vim